apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openzro-operator-config.fullname" . }}
  labels:
    {{- include "openzro-operator-config.labels" . | nindent 4 }}
rules:
- apiGroups:
  - openzro.io
  resources:
  - ozresources
  verbs:
  - patch
  - update
  - list
  - watch
  - create
  - delete
- apiGroups:
  - openzro.io
  resources:
  - ozroutingpeers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openzro.io
  resources:
  - ozresources/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openzro-operator-config.fullname" . }}
  labels:
    {{- include "openzro-operator-config.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "openzro-operator-config.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "openzro-operator-config.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
