fullnameOverride: "openzro-api-gateway"

controller:
  replicaCount: 1
  allowSnippetAnnotations: true
  nodeSelector:
    kubernetes.io/os: null
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: false
  ingressClassResource:
    name: openzro-api-gateway
    controllerValue: k8s.io/openzro-api-gateway
  ingressClass: openzro-api-gateway
  config:
    ssl-redirect: "true"
