{{- if and .Values.management.enabled .Values.management.pdb.enabled (gt (.Values.management.replicaCount | int) 1) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openzro.fullname" . }}-management
  namespace: {{ include "openzro.namespace" . }}
  labels:
    {{- include "openzro.management.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openzro.management.selectorLabels" . | nindent 6 }}
  {{- if .Values.management.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.management.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.management.pdb.minAvailable }}
  {{- end }}
{{- end -}}
