{{- if and .Values.signal.enabled .Values.signal.pdb.enabled (gt (.Values.signal.replicaCount | int) 1) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openzro.fullname" . }}-signal
  namespace: {{ include "openzro.namespace" . }}
  labels:
    {{- include "openzro.signal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openzro.signal.selectorLabels" . | nindent 6 }}
  {{- if .Values.signal.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.signal.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.signal.pdb.minAvailable }}
  {{- end }}
{{- end -}}
